import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { Roboto, Neonderthaw } from "next/font/google";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./styles/theme";
import "@/app/styles/globals.css";
import { CssBaseline } from "@mui/material";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

const neonderthaw = Neonderthaw({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-neonderthaw",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <CssBaseline />
      <html lang="en">
        <body
          className={`${roboto.variable} ${neonderthaw.variable}`}
        >
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>{children}</ThemeProvider>
          </AppRouterCacheProvider>
        </body>
      </html>
    </>
  );
}
